config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  root "users#index"
  #get 'users/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post :auth, to: 'authentication#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', optional: true
  belongs_to :post, optional: true
  after_destroy :decrement_comment_counter
  after_create :update_comment_counter

  def update_comment_counter
    post = Post.find_by(id: post_id)
    return unless post

    post.update(comments_counter: Comment.where(post_id:).count)
  end

  def decrement_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/json_token.rb
class JsonToken
  def self.encode(payload)
    JWT.encode payload, Rails.application.secrets.secret_key_base
  end

  def self.decode(token)
    JWT.decode(token, Rails.application.secrets.secret_key_base).first
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', optional: true
  belongs_to :post, optional: true

  after_create :update_like_counter

  def update_like_counter
    post = Post.find_by(id: post_id)
    return unless post

    post.update(likes_counter: Like.where(post_id:).count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', optional: true
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  after_destroy :update_post_counter
  after_create :update_post_counter

  def update_post_counter
    user = User.find_by(id: author_id)
    return unless user

    user.update(posts_counter: Post.where(author_id:).count)
  end

  def most_recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def most_recent_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :authenticate_token!

  before_action :set_default_format

  private

  def set_default_format
    request.format = :json
  end

  def authenticate_token!
    payload = JsonToken.decode(auth_token)
    @current_user = User.find(payload['sub'])
  rescue JWT::VerificationError
    render json: { errors: ['Invalid auth token'] }, status: :unauthorized
  end

  def auth_token
    @auth_token ||= request.headers.fetch('Authorization', '').split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LoadAndAuthorizeResource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  # protect_from_forgery with: :exception
  # protect_from_forgery with: :null_session

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :role) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(author_id: current_user.id, post_id: params[:post_id], **comment_params)
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to user_posts_path(params[:user_id])
    else
      flash[:alert] = 'Comment not created'
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    @comment.destroy
    redirect_to request.referrer
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(author_id: current_user.id, post_id: params[:post_id])
    if @like.save
      flash[:notice] = 'Like created successfully'
    else
      flash[:alert] = 'Like not created'
    end
    redirect_to user_posts_path(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_resource through: :current_user
  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
    @posts = Post.all
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by_id params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author_id: current_user.id, **post_params)
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_posts_path(params[:user_id])
    else
      flash[:alert] = 'Post not created'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session.delete(:current_user_id)
    flash[:notice] = 'Session have been closed successfully!'
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_comments.html.erb
<ul class="user comment">
<% if post.comments.any? %>
    <% post.comments.each do |comment| %>
    <li class="content-comment">
        <p class="content-commentt">
            <%= User.find(comment.author_id).name %>:<%= comment.text %>
            <% if can? :destroy , @post %>
                <%= button_to '', user_post_comment_path(@user , post , comment), method: :delete, style: "background-image: url(#{asset_path('delete.svg')})", class: "delete-btn" %>
            <%end%>
        </p>
    </li>
    <% end %>
    <% else %>
    <h3 class="no-comments">No hay comentarios</h3>

  
<% end %>
</ul>

app/views/shared/_form.html.erb
<%= form_with model: form_object, url: form_url, class: 'form' do |form| %>
    <h1 class="new-type">Add a new <%= type%></h1>
    <% if type == "post"%>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div class="field">
    
        <%= form.label :text %>
        <%= form.text_area :text %>
    </div>
    <div class="actions">
        <%= form.submit(class:'submit-btn') %>
    </div>
    <% elsif type == "comment" %>
    <div class="field">
        <%= form.label :text %>
        <%= form.text_area :text %>
    </div>
    <div class="actions">
        <%= form.submit(class:'submit-btn') %>
    </div>
    <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="navbar">
    <h1 class="header-title">My Blog</h1>
    <ul class="user-links">
    <% if user_signed_in? %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"signup-button"%>
    <% else %>
        <li> <%= link_to "Login", new_user_session_path, class:"signup-button" %></li>
        |
        <li> <%= link_to "Register", new_user_registration_path, class:"signup-button" %></li>
    <% end %>
    </ul>
  </nav>
</header>

app/views/shared/_user.html.erb
<li class="user-main">
    <img src="<%= user.photo %>" class="image">
    <div class="user-container">
        <h1 class="user-name"><%= link_to user.name, user_path(user) %></h1>
        <p class="number-posts">Number of posts: <%= user.posts.count %></p>
    </div>
</li>

app/views/shared/_user_posts.html.erb
<ul class="users ad-size">
        <% posts.each_with_index do |post, index| %>
            <li class="ind-post">
                <h2 class="text-format counter">Post #<%=index+1%>: <%= link_to post.title, user_post_path(@user, post) %></h2>
                <p class="text-format counter"><%= post.text %></p>
                <%= form_with url: user_post_likes_path(@user.id, post.id), class:'like-form' do |form|%>
                    <%= form.submit '', class: 'like-btn', style: "background-image: url(#{asset_path('like.svg')})" %>
                <% end %>
                <p class="text-format number-posts adj-end">Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
                <% if ren===0 %>
                    <hr class="separator">
                    <%= render 'shared/comments', post: post %>
                <% end %>            
            </li> 
            
            

            
        <% end %>
    </ul>